; WaveScribe Installer Script
; Generated by build_windows.py

#define MyAppName "WaveScribe"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "WaveScribe"
#define MyAppURL "https://wavescribe.ai"
#define MyAppExeName "WaveScribe.exe"

[Setup]
AppId={{B8F4A3D2-1C5E-4A9B-8D6F-7E2C3A1B5D9F}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=
PrivilegesRequired=admin
OutputDir=C:\Users\CPU\Documents\Programas\codex\wavescribe\installer
OutputBaseFilename=WaveScribe-Setup-{#MyAppVersion}
SetupIconFile=C:\Users\CPU\Documents\Programas\codex\wavescribe\assets\icon.ico
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"; Flags: checkedonce

[Files]
Source: "C:\Users\CPU\Documents\Programas\codex\wavescribe\dist\WaveScribe\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: postinstall nowait skipifsilent

[UninstallRun]
Filename: "{app}\unins000.exe"; RunOnceId: "DeleteConfig"
